#!/bin/sh
# This script file is to re-execute test cases and merge test result on Robot framework
# usage: ./run_robot.sh any_robot_command test_suite
# note: cannot execute command within ', ex. -t 'test case'
# Reference: http://laurent.bristiel.com/re-executing-failed-test-cases-and-merging-outputs-with-robot-framework/

# clean previous output files
rm -f report/output.xml
rm -f report/rerun.xml
rm -f report/first_run_log.html
rm -f report/second_run_log.html
rm -f report/xunit.xml

run_with_tag=''

if [ ! -z "$TAG" ]; then
    run_with_tag='-i '$TAG
fi
 
echo
echo "#######################################"
echo "# Running portfolio a first time      #"
echo "#######################################"
echo
pabot $run_with_tag -x xunit.xml --outputdir report $@
res=$?

# we stop the script here if all the tests were OK
if [ $res -eq 0 ]; then
    echo "we don't run the tests again as everything was OK on first try"
    exit 0  
fi
# otherwise we go for another round with the failing tests
 
# we keep a copy of the first log file
cp report/log.html  report/first_run_log.html
 
# we launch the tests that failed
echo
echo "#######################################"
echo "# Running again the tests that failed #"
echo "#######################################"
echo
pabot --outputdir report --rerunfailed report/output.xml -x xunit.xml --output rerun.xml $@
res=$?
# Robot Framework generates file rerun.xml

if [ $res -ne 0 ]; then
    RES=true
fi
 
# we keep a copy of the second log file
cp report/log.html  report/second_run_log.html
 
# Merging output files
echo
echo "########################"
echo "# Merging output files #"
echo "########################"
echo
rebot --nostatusrc --outputdir report --output output.xml --merge report/output.xml  report/rerun.xml
# Robot Framework generates a new output.xml

if [ $RES ]; then
    exit 1  
fi
